-- +goose Up
CREATE TABLE users(
id UUID PRIMARY KEY NOT NULL,
name TEXT UNIQUE NOT NULL,
created_at TIMESTAMP NOT NULL DEFAULT NOW(),
updated_at TIMESTAMP NOT NULL DEFAULT NOW ()
);
CREATE TABLE feeds(
id UUID PRIMARY KEY NOT NULL,
name TEXT NOT NULL,
url TEXT UNIQUE NOT NULL,
user_id UUID REFERENCES users ON DELETE CASCADE NOT NULL,
created_at TIMESTAMP NOT NULL DEFAULT NOW(),
updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);


-- +goose Down
DROP TABLE feeds;
DROP TABLE users;

